apiVersion: apps/v1
kind: Deployment
metadata: 
  name: nginx-app
  labels: 
    app: nginx
spec:
  replicas:  2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      name: nginx-pod
      labels:
        app: nginx
    spec:
      containers: 
        - name: nginx-container
          image: nginx
  
  