apiVersion: apps/v1
kind: Deployment
metadata: 
  name: nginx-app
  labels: 
    app: nginx
spec:
  replicas:  3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      name: nginx-pod
      labels:
        app: nginx
    spec:
      containers: 
        - name: nginx-container
          image: nginx

---
apiVersion: v1
kind: Service
metadata:
  name: nginx-svc
spec:
  selector: 
      app: nginx  
  ports:
    - port: 3001
      targetPort: 80
  
  